embabel.agent.platform.models.openai.base-url=http://localhost:11434
embabel.agent.platform.models.openai.api-key=unused
embabel.models.default-llm=library/llama3.2
#  Other available personalities: severance, colossus, hitchhiker, montypython.
# embabel.agent.logging.personality=starwars
